version: '3'

services:
    api:
        container_name: ${APP_CONTAINER_NAME}
        build: .        
        command: >
            sh -c "python manage.py makemigrations
            && python manage.py shell < ./app/createdb/__init__.py
            && python manage.py migrate
            && python manage.py runserver 0.0.0.0:8000"
                
        ports:
            - '${APP_PUBLIC_PORT}:8000'
        volumes:
            - .:/app # mount code in local vs code in docker

        restart: ${APP_CONTAINER_RESTART} #always

        environment:
            APP_ROOT_USER: ${APP_ROOT_USER}
            APP_ROOT_PASSWORD: ${APP_ROOT_PASSWORD}
            APP_ROOT_EMAIL: ${APP_ROOT_EMAIL}
            MARIADB_CONTAINER_NAME: ${MARIADB_CONTAINER_NAME}
            MARIADB_PORT: ${MARIADB_PORT}
            MARIADB_ROOT_USER: ${MARIADB_ROOT_USER}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            REDIS_CONTAINER_NAME: ${REDIS_CONTAINER_NAME}

        depends_on:
            - mariadb
            - redis

    mariadb:
        # Image Version: 
        image: mariadb
        container_name: ${MARIADB_CONTAINER_NAME}
        ports:
            - ${MARIADB_PUBLIC_PORT}:${MARIADB_PORT}
        # command: --default-authentication-plugin=mysql_native_password
        restart: ${MARIADB_CONTAINER_RESTART}
        environment:
            MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            # Auto Create DB
            MYSQL_DATABASE: ${MARIADB_DATABASE}
    
    phpmyadmin:
        # Image Version: 
        image: phpmyadmin/phpmyadmin
        container_name: ${PHPMYADMIN_CONTAINER_NAME}
        links:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: ${MARIADB_PORT}
            PMA_ARBITRARY: 1
        restart: ${PHPMYADMIN_CONTAINER_RESTART}
        ports:
            - ${PHPMYADMIN_PUBLIC_PORT}:80

    redis:
        # Image Version: 
        image: "redis:alpine"
        container_name: ${REDIS_CONTAINER_NAME}


networks: # Sử dụng network đã có sẵn
    default:
        external:
            name: mysql_default